Anti-Aim Grenade Fix
danielkrupinski/Osiris pull request #1525
Opened 2020-05-04 14:32 UTC by 3Ld4D

2020-05-04 16:57 UTC, egssy0 commented
ammmm. i cant include localplayer.h it says cant include localplayer.h
i added them to entity.h and i tried in game it gives error

2020-05-04 17:27 UTC, notgoodusename commented
bruh

2020-05-04 18:06 UTC, egssy0 commented
I got error code : // "localEntity && *localentity"

Line : 23
Please help

2020-05-04 19:54 UTC, 3Ld4D commented
that has nothing to do with this...

2020-05-04 20:50 UTC, egssy0 commented
i downloaded latest osiris and updated for me i give it for my 3 h and i fixed it thanks!

2020-05-04 21:48 UTC, egssy0 commented
https://prnt.sc/saxvyp **I having this now bruH**

2020-05-04 22:20 UTC, egssy0 commented
i got it knife is problem it says when 
i got my flip knife and i attack with it it gives this error

2020-05-04 22:20 UTC, egssy0 commented
what can i do
`#pragma once

enum class WeaponId : short {
    Deagle = 1,
    Elite,
    Fiveseven,
    Glock,
    Ak47 = 7,
    Aug,
    Awp,
    Famas,
    G3SG1,
    GalilAr = 13,
    M249,
    M4A1 = 16,
    Mac10,
    P90 = 19,
    Mp5sd = 23,
    Ump45,
    Xm1014,
    Bizon,
    Mag7,
    Negev,
    Sawedoff,
    Tec9,
    Taser,
    Hkp2000,
    Mp7,
    Mp9,
    Nova,
    P250,
    Scar20 = 38,
    Sg553,
    Ssg08,
    GoldenKnife,
    M4a1_s = 60,
    Usp_s,
    Cz75a = 63,
    Revolver,
    GhostKnife = 80,
    Bayonet = 500,
    Flip = 505,
    Gut,
    Karambit,
    M9Bayonet,
    Huntsman,
    Falchion = 512,
    Bowie = 514,
    Butterfly,
    Daggers,
    Ursus = 519,
    Navaja,
    Stiletto = 522,
    Talon,
    GloveStuddedBloodhound = 5027,
    GloveT,
    GloveCT,
    GloveSporty,
    GloveSlick,
    GloveLeatherWrap,
    GloveMotorcycle,
    GloveSpecialist,
    GloveHydra,
    Flash = 43,
    Grenade,
    Smoke,
    Molotov,
    Decoy,
    IncGrenade,

};

constexpr int getWeaponIndex(WeaponId weaponId) noexcept
{
    switch (weaponId) {
    default: return 0;

    case WeaponId::Glock: return 1;
    case WeaponId::Hkp2000: return 2;
    case WeaponId::Usp_s: return 3;
    case WeaponId::Elite: return 4;
    case WeaponId::P250: return 5;
    case WeaponId::Tec9: return 6;
    case WeaponId::Fiveseven: return 7;
    case WeaponId::Cz75a: return 8;
    case WeaponId::Deagle: return 9;
    case WeaponId::Revolver: return 10;

    case WeaponId::Nova: return 11;
    case WeaponId::Xm1014: return 12;
    case WeaponId::Sawedoff: return 13;
    case WeaponId::Mag7: return 14;
    case WeaponId::M249: return 15;
    case WeaponId::Negev: return 16;

    case WeaponId::Mac10: return 17;
    case WeaponId::Mp9: return 18;
    case WeaponId::Mp7: return 19;
    case WeaponId::Mp5sd: return 20;
    case WeaponId::Ump45: return 21;
    case WeaponId::P90: return 22;
    case WeaponId::Bizon: return 23;

    case WeaponId::GalilAr: return 24;
    case WeaponId::Famas: return 25;
    case WeaponId::Ak47: return 26;
    case WeaponId::M4A1: return 27;
    case WeaponId::M4a1_s: return 28;
    case WeaponId::Ssg08: return 29;
    case WeaponId::Sg553: return 30;
    case WeaponId::Aug: return 31;
    case WeaponId::Awp: return 32;
    case WeaponId::G3SG1: return 33;
    case WeaponId::Scar20: return 34;

    case WeaponId::Taser: return 39;

    case WeaponId::GhostKnife:return 47;
    case WeaponId::GoldenKnife:return 48;
    case WeaponId::Talon:return 49;
    case WeaponId::Stiletto:return 50;
    case WeaponId::Navaja:return 51;
    case WeaponId::Ursus: return 52;
    case WeaponId::Daggers:return 53;
    case WeaponId::Butterfly:return 54;
    case WeaponId::Bowie:return 55;
    case WeaponId::Falchion:return 56;
    case WeaponId::Huntsman:return 57;
    case WeaponId::M9Bayonet: return 58;
    case WeaponId::Karambit:return 59;
    case WeaponId::Gut:return 60;
    case WeaponId::Flip: return 61;
    case WeaponId::Bayonet: return 62;
    case WeaponId::Flash: return 41;
    case WeaponId::Decoy: return 42;
    case WeaponId::Grenade: return 43;
    case WeaponId::IncGrenade: return 44;
    case WeaponId::Molotov: return 45;
    case WeaponId::Smoke: return 46;

    }
}

constexpr int getWeaponClass(WeaponId weaponId) noexcept
{
    switch (weaponId) {
    default: return 0;

    case WeaponId::Glock:
    case WeaponId::Hkp2000:
    case WeaponId::Usp_s:
    case WeaponId::Elite:
    case WeaponId::P250:
    case WeaponId::Tec9:
    case WeaponId::Fiveseven:
    case WeaponId::Cz75a:
    case WeaponId::Deagle:
    case WeaponId::Revolver: return 35;

    case WeaponId::Nova:
    case WeaponId::Xm1014:
    case WeaponId::Sawedoff:
    case WeaponId::Mag7:
    case WeaponId::M249:
    case WeaponId::Negev: return 36;

    case WeaponId::Mac10:
    case WeaponId::Mp9:
    case WeaponId::Mp7:
    case WeaponId::Mp5sd:
    case WeaponId::Ump45:
    case WeaponId::P90:
    case WeaponId::Bizon: return 37;

    case WeaponId::GalilAr:
    case WeaponId::Famas:
    case WeaponId::Ak47:
    case WeaponId::M4A1:
    case WeaponId::M4a1_s:
    case WeaponId::Ssg08:
    case WeaponId::Sg553:
    case WeaponId::Aug:
    case WeaponId::Awp:
    case WeaponId::G3SG1:
    case WeaponId::Scar20: return 38;

    case WeaponId::Flash:
    case WeaponId::Decoy:
    case WeaponId::Grenade:
    case WeaponId::IncGrenade:
    case WeaponId::Molotov:
    case WeaponId::Smoke: return 40;


    }
}
`

2020-05-04 22:26 UTC, 3Ld4D commented
i don't see the problem with this tho
`Flip = 505`

2020-05-04 22:31 UTC, egssy0 commented
idk but when i get my flip knife this error occures

2020-05-04 22:33 UTC, egssy0 commented
it does in m9 bayonet too in my opinion it does at all knives

2020-05-04 22:35 UTC, 3Ld4D commented
everything is working fine i just tested it.

2020-05-04 22:39 UTC, egssy0 commented
okay i will download and edit for my self again thanks dude!

2020-05-05 16:56 UTC, egssy0 commented
now it crashes when i throw flashbang lul

2020-05-05 16:59 UTC, 3Ld4D commented
> now it crashes when i throw flashbang lul

listen man everything is fine, don't try to modify the code when u don't know how to.

2020-05-05 17:06 UTC, notgoodusename commented
you forgot to do         
if (!weaponClass)
            return;
also here is the weaponid with every knife
#pragma once

enum class WeaponId : short {
    Deagle = 1,
    Elite,
    Fiveseven,
    Glock,
    Ak47 = 7,
    Aug,
    Awp,
    Famas,
    G3SG1,
    GalilAr = 13,
    M249,
    M4A1 = 16,
    Mac10,
    P90 = 19,
    Mp5sd = 23,
    Ump45,
    Xm1014,
    Bizon,
    Mag7,
    Negev,
    Sawedoff,
    Tec9,
    Taser,
    Hkp2000,
    Mp7,
    Mp9,
    Nova,
    P250,
    Scar20 = 38,
    Sg553,
    Ssg08,
    Knife = 42,
    Flashbang = 43,
    HeGrenade = 44,
    SmokeGrenade = 45,
    Molotov = 46,
    Decoy = 47,
    IncGrenade = 48,
    GoldenKnife,
    C4,
    KnifeT = 59,
    M4a1_s = 60,
    Usp_s,
    Cz75a = 63,
    Revolver,
    GhostKnife = 80,
    Bayonet = 500,
    KnifeCss = 503,
    Flip = 505,
    Gut,
    Karambit,
    M9Bayonet,
    Huntsman,
    Falchion = 512,
    Bowie = 514,
    Butterfly,
    Daggers,
    Cord,
    Canis,
    Ursus,
    Navaja,
    KnifeOutdoor,
    Stiletto,
    Talon,
    Skeleton = 525,
    GloveStuddedBloodhound = 5027,
    GloveT,
    GloveCT,
    GloveSporty,
    GloveSlick,
    GloveLeatherWrap,
    GloveMotorcycle,
    GloveSpecialist,
    GloveHydra
};

constexpr int getWeaponIndex(WeaponId weaponId) noexcept
{
    switch (weaponId) {
    default: return 0;

    case WeaponId::Glock: return 1;
    case WeaponId::Hkp2000: return 2;
    case WeaponId::Usp_s: return 3;
    case WeaponId::Elite: return 4;
    case WeaponId::P250: return 5;
    case WeaponId::Tec9: return 6;
    case WeaponId::Fiveseven: return 7;
    case WeaponId::Cz75a: return 8;
    case WeaponId::Deagle: return 9;
    case WeaponId::Revolver: return 10;

    case WeaponId::Nova: return 11;
    case WeaponId::Xm1014: return 12;
    case WeaponId::Sawedoff: return 13;
    case WeaponId::Mag7: return 14;
    case WeaponId::M249: return 15;
    case WeaponId::Negev: return 16;

    case WeaponId::Mac10: return 17;
    case WeaponId::Mp9: return 18;
    case WeaponId::Mp7: return 19;
    case WeaponId::Mp5sd: return 20;
    case WeaponId::Ump45: return 21;
    case WeaponId::P90: return 22;
    case WeaponId::Bizon: return 23;

    case WeaponId::GalilAr: return 24;
    case WeaponId::Famas: return 25;
    case WeaponId::Ak47: return 26;
    case WeaponId::M4A1: return 27;
    case WeaponId::M4a1_s: return 28;
    case WeaponId::Ssg08: return 29;
    case WeaponId::Sg553: return 30;
    case WeaponId::Aug: return 31;
    case WeaponId::Awp: return 32;
    case WeaponId::G3SG1: return 33;
    case WeaponId::Scar20: return 34;

    case WeaponId::Taser: return 39;
    case WeaponId::Flashbang:return 41;
    case WeaponId::Decoy:return 42;
    case WeaponId::HeGrenade:return 43;
    case WeaponId::IncGrenade:return 44;
    case WeaponId::Molotov:return 45;
    case WeaponId::SmokeGrenade: return 46;

    case WeaponId::GhostKnife:return 47;
    case WeaponId::GoldenKnife:return 48;
    case WeaponId::Talon:return 49;
    case WeaponId::Stiletto:return 50;
    case WeaponId::Navaja:return 51;
    case WeaponId::Ursus: return 52;
    case WeaponId::Daggers:return 53;
    case WeaponId::Butterfly:return 54;
    case WeaponId::Bowie:return 55;
    case WeaponId::Falchion:return 56;
    case WeaponId::Huntsman:return 57;
    case WeaponId::M9Bayonet: return 58;
    case WeaponId::Karambit:return 59;
    case WeaponId::Gut:return 60;
    case WeaponId::Flip: return 61;
    case WeaponId::Bayonet: return 62;
    case WeaponId::Knife: return 64;
    }
}
constexpr int getWeaponClass(WeaponId weaponId) noexcept
{
    switch (weaponId) {
    default: return 0;

    case WeaponId::Glock:
    case WeaponId::Hkp2000:
    case WeaponId::Usp_s:
    case WeaponId::Elite:
    case WeaponId::P250:
    case WeaponId::Tec9:
    case WeaponId::Fiveseven:
    case WeaponId::Cz75a:
    case WeaponId::Deagle:
    case WeaponId::Revolver: return 35;

    case WeaponId::Nova:
    case WeaponId::Xm1014:
    case WeaponId::Sawedoff:
    case WeaponId::Mag7:
    case WeaponId::M249:
    case WeaponId::Negev: return 36;

    case WeaponId::Mac10:
    case WeaponId::Mp9:
    case WeaponId::Mp7:
    case WeaponId::Mp5sd:
    case WeaponId::Ump45:
    case WeaponId::P90:
    case WeaponId::Bizon: return 37;

    case WeaponId::GalilAr:
    case WeaponId::Famas:
    case WeaponId::Ak47:
    case WeaponId::M4A1:
    case WeaponId::M4a1_s:
    case WeaponId::Ssg08:
    case WeaponId::Sg553:
    case WeaponId::Aug:
    case WeaponId::Awp:
    case WeaponId::G3SG1:
    case WeaponId::Scar20: return 38;

    case WeaponId::Flashbang:
    case WeaponId::Decoy:
    case WeaponId::HeGrenade:
    case WeaponId::IncGrenade:
    case WeaponId::Molotov:
    case WeaponId::SmokeGrenade: return 40;

    case WeaponId::Knife: //42
    case WeaponId::GoldenKnife: //49
    case WeaponId::KnifeT: //59
    case WeaponId::GhostKnife: //80
    case WeaponId::Bayonet: //500
    case WeaponId::KnifeCss: //503
    case WeaponId::Flip: //505
    case WeaponId::Gut: //506
    case WeaponId::Karambit: //507
    case WeaponId::M9Bayonet: //508
    case WeaponId::Huntsman: //509
    case WeaponId::Falchion: //512
    case WeaponId::Bowie: //514
    case WeaponId::Butterfly: //515
    case WeaponId::Daggers: //516
    case WeaponId::Cord: //517
    case WeaponId::Canis: //518
    case WeaponId::Ursus: //519
    case WeaponId::Navaja: //520
    case WeaponId::KnifeOutdoor: //521
    case WeaponId::Stiletto: //522
    case WeaponId::Talon: //523
    case WeaponId::Skeleton:  return 63; //525 
    case WeaponId::Taser: return 66;
    }
}

2020-05-05 17:12 UTC, 3Ld4D commented
@notgoodusename it can't be invalid, so it doesn't do anything
```cpp
default: return 0;

2020-05-05 17:13 UTC, notgoodusename commented
put it anyway

2020-05-05 17:15 UTC, 3Ld4D commented
> put it anyway

there's no need since it can't be invalid, why do u think @danielkrupinski didn't put it in aimbot

2020-05-05 17:16 UTC, notgoodusename commented
ok

2020-09-07 18:36 UTC, danielkrupinski requested changes

2020-09-07 18:36 UTC, danielkrupinski commented on Osiris/SDK/WeaponId.h
> +    case WeaponId::Smoke: return 46;
This will make aimbot / triggerbot crash. `getWeaponIndex()` function is only meant to be used in aimbot & triggerbot.

2020-09-07 18:36 UTC, danielkrupinski commented on Osiris/SDK/WeaponId.h
> +    case WeaponId::Smoke: return 40;
This will make aimbot / triggerbot crash. `getWeaponClass()` function is only meant to be used in aimbot & triggerbot.

2020-09-09 22:00 UTC, closed without merging

2020-09-09 22:00 UTC, 3Ld4D commented
i will make a new pull.