Fast ladder climb
danielkrupinski/Osiris pull request #2182
Opened 2020-09-14 13:56 UTC by NewYearsGift

2020-09-14 13:58 UTC, dapaster commented
any preview?

2020-09-14 15:49 UTC, Cyk-Fad commented
maybe it makes legitbot better

2020-09-14 17:45 UTC, r3muxd commented
it's not a legit feature, your viewangle goes straight down or straight up when you get on a ladder

2020-09-14 18:02 UTC, danielkrupinski requested changes

2020-09-14 18:02 UTC, danielkrupinski commented on Osiris/Hacks/Misc.cpp
> +            }
This could be condensed to < 10 lines of code.

2020-09-14 23:11 UTC, 3Ld4D commented
this should be done with sidemove and forward move, you can take a look at proper autostrafer which doesn't change viewangles

2020-09-15 11:21 UTC, newcommerdontblame commented
Dude its super easy to do without cheat and this  viewangle thing will cause ow ban for sure

2021-08-06 08:09 UTC, closed without merging