Profile Changer
danielkrupinski/Osiris pull request #2503
Opened 2021-01-20 00:27 UTC by caiocinel

Warning: This is a Pull Request without any merge interest, it only serves as a basis for someone who wants to add a ProfileChanger to their build.

The hook method is vfunc, it needs adaptation for the new libraries.

The added files already have full capacity for adding an InventoryChanger / MedalChanger, but I didn't have the patience for that.

If you know how to optimize or extend, feel free to share, that I will try to do the best (or make a pull request on the fork).

In short: it has what it takes to function and nothing else.

2021-01-20 01:30 UTC, TarwzDev commented
Aprendeu omigo

2021-01-20 17:48 UTC, linuxer9 requested changes

2021-01-20 17:48 UTC, linuxer9 commented on Osiris/Changer/valve_parser.h
> +static const char smalll_compressed_data_base85[32600 + 1] =
yo , remove that junk!

2021-01-21 04:12 UTC, doggobot-owner commented
You need to add a config system, it doesnt save

2021-01-21 13:32 UTC, Scui1 commented
can't change ranks on wingman and dangerzone, nice paste 😂

2021-01-21 14:04 UTC, caiocinel commented
Be a little less ignorant and read the description of the pull request.

Em qui., 21 de jan. de 2021 às 10:32, Scui1 <notifications@github.com>
escreveu:

> can't change ranks on wingman and dangerzone, nice paste 😂
>
> —
> You are receiving this because you authored the thread.
>

2021-01-21 17:39 UTC, doggobot-owner commented
this should be developed more and added medal and inventory changer, ngl
also add config system
goodluck

2021-01-21 19:13 UTC, thisisnotagithub commented
works as it should thank you for your contribution. i will continue to try and develop this project and add a medal changer, i would appreciate it if other people tried as well

2021-01-24 05:43 UTC, MirzaGorgAli commented
Hi and thank you @caiocinel for this awesome pull. Can anyone make medal changer that other people be able to see medals on my profile in lobby (not in the match only when they join my lobby)?
*Sorry about my ENGLISH*

2021-02-11 21:27 UTC, linuxer9 commented
I'm working on the inventory changer, I finally managed to make it work but I have "a stupid" issue, I can't get steam account ID 
`uint32_t steamid = memory->SteamUser->GetSteamID().GetAccountID();`
I tried adding this code to memory.cpp
`ISteamUser* SteamUser = SteamClient->GetISteamUser((void*)1, (void*)1, "SteamUser019");`
but the game is crashing..
I manually hardcoded my steam ID and it works fine, 
@caiocinel

2021-02-11 23:28 UTC, caiocinel commented
> I'm working on the inventory changer, I finally managed to make it work but I have "a stupid" issue, I can't get steam account ID
> I manually hardcoded my steam ID and it works fine,
> @caiocinel

Take a look at how Daniel does it on GOESP:

https://github.com/danielkrupinski/GOESP/search?q=steamid

2021-02-12 00:38 UTC, linuxer9 commented
> 
> Take a look at how Daniel does it on GOESP:
> 
> https://github.com/danielkrupinski/GOESP/search?q=steamid

Thanks a took a look at it before and it's not what I want, It grabs steam IDs of entities during the game, so it's not helpful if the user is in the main menu (i.e. LocalPlayer doesn't exist)

2021-02-12 02:17 UTC, linuxer9 commented
I feel dumb, I set the steam id to 0 and it still works
```
void Inventory::ApplyMedals(ProtoWriter& object)
{
	uint32_t MedalIndex = 970;// config->medalChanger.medals;
	uint64_t steamid = 0;
...
```
do you think this might have side effects?

2021-02-12 16:38 UTC, Scui1 commented
> 
> 
> I'm working on the inventory changer, I finally managed to make it work but I have "a stupid" issue, I can't get steam account ID
> `uint32_t steamid = memory->SteamUser->GetSteamID().GetAccountID();`
> I tried adding this code to memory.cpp
> `ISteamUser* SteamUser = SteamClient->GetISteamUser((void*)1, (void*)1, "SteamUser019");`
> but the game is crashing..
> I manually hardcoded my steam ID and it works fine,
> @caiocinel

wtf are you doing? Why are you passing 1 as values for handles? maybe read the [documentation](https://partner.steamgames.com/doc/api/ISteamClient)

2021-02-13 05:40 UTC, MirzaGorgAli commented
I'm noob but maybe :
"ISteamUser* SteamUser;" in the "memory.h"
"SteamUser = (ISteamUser*)SteamClient->GetISteamUser((void*)1, (void*)1, "SteamUser019");" in the "memory.cpp"

Test an tell me :D

2021-02-13 14:58 UTC, caiocinel commented
Memory.cpp:
` SteamUser = SteamClient->GetISteamUser((void*)1, (void*)1, "SteamUser019"
);  `

Memory.h
` ISteamUser* SteamUser;  `

Call with:
memory->SteamUser->GetSteamID().GetAccountID();

Em sáb., 13 de fev. de 2021 às 02:40, MirzaGorgAli <notifications@github.com>
escreveu:

> I'm noob but maybe :
> "ISteamUser* SteamUser;" in the "memory.h"
> "SteamUser = (ISteamUser*)SteamClient->GetISteamUser((void*)1, (void*)1,
> "SteamUser019");" in the "memory.cpp"
>
> Test an tell me :D
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/danielkrupinski/Osiris/pull/2503#issuecomment-778567606>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQKCYBGAJZDODZWAMGHI73S6YGGJANCNFSM4WJZVILA>
> .
>

2021-02-13 16:58 UTC, linuxer9 commented
> 
> wtf are you doing? Why are you passing 1 as values for handles? maybe read the [documentation](https://partner.steamgames.com/doc/api/ISteamClient)

I have no idea of I what I'm doing, actually but I looked at "GetISteamGenericInterface" it's the function and he passed 1 for both hSteamUser and hSteamPipe, so I did the same. I appreciate your tip :)

I finally solved it, thanks to @MirzaGorgAli and @caiocinel, your both solutions did actually work :) 👍

2021-02-28 21:04 UTC, zioloprime commented
How to make usage of this/?

2021-03-22 19:09 UTC, FlameProfi commented
autoupdate skins don't work, please fix

2021-03-22 23:04 UTC, caiocinel commented
> autoupdate skins don't work, please fix

See what causes the problem and do a review, with that I can fix the problem.

This project is an example, it is far from ideal.

2021-03-23 03:11 UTC, linuxer9 commented
> 
> 
> autoupdate skins don't work, please fix

changing local inventory doesn't change your the server side inventory.
the game still gets your items from GC server.
so in order to make inventory changer work in game, you have two options:
- either force fallback paintkit on weapons according to the equipped weapon slot.
- or, dynamically get the item ID of equipped slot and set your current weapon item id to that id from local inventory.
you still need to change models, fix animations of knives and make gloves, just like the current skin changer.

2021-03-28 22:47 UTC, caiocinel commented
I'm working on a better ProfileChanger, allowing me to change Wingman and DZ as well.

2021-03-28 22:47 UTC, closed without merging

2021-05-24 11:32 UTC, SquidmarcHD commented
hey can i get your discord by any chance?

2021-05-24 11:51 UTC, caiocinel commented
Caillou#9999

Em seg., 24 de mai. de 2021 às 08:32, SquidmarcHD ***@***.***>
escreveu:

> hey can i get your discord by any chance?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/danielkrupinski/Osiris/pull/2503#issuecomment-846981592>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQKCYHJYUGGRJC5XNMWRV3TPI2M3ANCNFSM4WJZVILA>
> .
>

2021-05-25 17:19 UTC, SquidmarcHD commented
would be cool if you also accept it :+1:

2021-05-25 19:34 UTC, caiocinel commented
Unfortunately this week I'm busy, maybe on Saturday.

Em ter., 25 de mai. de 2021 às 14:20, SquidmarcHD ***@***.***>
escreveu:

> would be cool if you also accept it 👍
>
> —
> You are receiving this because you modified the open/close state.
>

2022-07-13 20:27 UTC, alerion921 commented
Will this be updated?

2022-07-13 22:09 UTC, caiocinel commented
probably not

Em qua., 13 de jul. de 2022 às 17:27, alerion921 ***@***.***>
escreveu:

> Will this be updated?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/danielkrupinski/Osiris/pull/2503#issuecomment-1183645017>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQKCYGHNGIMKJDOVWL374DVT4RCDANCNFSM4WJZVILA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-05-28 09:22 UTC, buttonzero commented
does this work still, been lookin for a profile changer for a while cant seem to find one