Add vote revealer
danielkrupinski/Osiris pull request #2723
Opened 2021-03-22 10:22 UTC by mkot2

didn't test this so tell me if there are any problems

it outputs to console right now and it's just fine, but is there a way to output messages to chat and only have local player see them?

2021-03-22 12:24 UTC, Tothale commented
I have tried in gun race, working good.

2021-03-22 14:45 UTC, cristyanul commented
It works!

2021-03-22 15:20 UTC, KernCS commented
> but is there a way to output messages to chat and only have local player see them?

https://www.unknowncheats.me/forum/counterstrike-global-offensive/171375-printing-text-chat.html

2021-03-22 19:10 UTC, danielkrupinski requested changes

2021-03-22 19:10 UTC, danielkrupinski commented on Osiris/Hacks/Misc.cpp
> +            std::ostringstream str;
No need to use `std::ostringstream`.

2021-03-22 19:10 UTC, danielkrupinski commented on Osiris/Hacks/Misc.cpp
> +            str << interfaces->entityList->getEntity(event->getInt("entityid"))->getPlayerName() << " : ";
Entity nullptr check is missing.

2021-03-22 19:10 UTC, danielkrupinski commented on Osiris/Hacks/Misc.cpp
> +void Misc::voteRevealer(GameEvent* event = nullptr) {
`event` could be `GameEvent&` as the function does nothing when `event` is nullptr.

2021-03-23 13:02 UTC, danielkrupinski approved these changes

2021-03-23 15:47 UTC, merged

2021-03-23 15:48 UTC, danielkrupinski commented
Thank you for the contribution!