Some features
danielkrupinski/Osiris pull request #2951
Opened 2021-06-01 17:32 UTC by blackMasterLord

Add agents
Add ingame medal changer
Some fixes

2021-06-01 17:51 UTC, mkot2 commented
very nice

2021-06-01 22:39 UTC, wemanzoz commented
very nic

2021-06-02 10:45 UTC, blackMasterLord commented
> Can't add agents.

 fixed

2021-06-03 18:39 UTC, danielkrupinski requested changes

2021-06-03 18:39 UTC, danielkrupinski commented on Osiris/Hacks/InventoryChanger.cpp
> +                    _gameItems.emplace_back(Type::Agent, item->getRarity(), item->getWeaponId(), _paintKits.size() - 1, image);
`_paintKits.emplace_back(0, L"");` is for adding "vanilla" paint kits. Agents do not use paint kits at all so remove that line and replace `_paintKits.size() - 1` with zero.

2021-06-04 15:11 UTC, Xonn1com commented
![obraz](https://user-images.githubusercontent.com/64926921/120823556-d74e6d80-c557-11eb-8205-de07d52fcf0d.png)
Error while building?

2021-06-04 16:07 UTC, blackMasterLord commented
> ![obraz](https://user-images.githubusercontent.com/64926921/120823662-ef25f180-c557-11eb-81de-5ff7ab1ff5ba.png)
> 
> Help needed

sorry, my bad

> ![obraz](https://user-images.githubusercontent.com/64926921/120823662-ef25f180-c557-11eb-81de-5ff7ab1ff5ba.png)
> 
> Help needed

fixed

2021-06-04 17:28 UTC, mkot2 commented on Osiris/Hooks.cpp
> +static void __STDCALL dispatchUserMessage(int messageType, uint32_t arg, uint32_t length, void* data) noexcept
does this work on linux?

2021-06-04 18:29 UTC, blackMasterLord commented on Osiris/Hooks.cpp
> +static void __STDCALL dispatchUserMessage(int messageType, uint32_t arg, uint32_t length, void* data) noexcept
maybe.
idk

2021-06-05 11:03 UTC, Asviix commented
I'm guessing Medal only affects the visual of Client ? still doing god's work

2021-06-05 14:12 UTC, blackMasterLord commented
> I'm guessing Medal only affects the visual of Client ? still doing god's work

client side only

2021-06-08 04:14 UTC, wemanzoz commented
![csgo_pwkKXiwN06](https://user-images.githubusercontent.com/72364877/121121902-13811700-c853-11eb-838b-d75336e5f6cb.png)
knife logo on kill message doesnt change, whilst it works on normal osiris. pls fix @blackMasterLord

2021-06-08 12:07 UTC, blackMasterLord commented
> ![csgo_pwkKXiwN06](https://user-images.githubusercontent.com/72364877/121121902-13811700-c853-11eb-838b-d75336e5f6cb.png)
> knife logo on kill message doesnt change, whilst it works on normal osiris. pls fix @blackMasterLord

fixed

2021-06-08 13:27 UTC, wemanzoz commented
@blackMasterLord since dk added agent patches. remove or nah

2021-06-14 18:57 UTC, wirekuro commented
Dude can you make an other pr with only the Better Vote Revealer?

2021-06-14 20:04 UTC, uzdiiilekk commented
Can someone send me dll of this completed ? everytime i get error.. my discord is - uzdiiilekk_#3312

2021-06-15 06:44 UTC, wirekuro commented
https://github.com/blackMasterLord/Osiris-Some-features here's the project, if u keep getting errors try updating visual studio.

2021-06-15 06:45 UTC, wirekuro commented
> Can someone send me dll of this completed ? everytime i get error.. my discord is - uzdiiilekk_#3312

https://github.com/blackMasterLord/Osiris-Some-features here's the project, if u keep getting errors try updating visual studio.

2021-07-11 23:29 UTC, Alpha878 commented
@blackMasterLord do you think you are able to add lobby things and also troll options? Like you can see people locations, spam the lobby chat or send them 200 pop up errors?

2021-07-19 14:41 UTC, closed without merging

2021-10-18 04:44 UTC, wemanzoz commented
> @blackMasterLord is it possible for you to link me the branch for this pr?

can u instead make the better inv changer menu a seperate pr? @blackMasterLord