if mp_drop_knife_enable is 1
danielkrupinski/Osiris pull request #3094
Opened 2021-07-10 19:43 UTC by bruhmoment21

2021-07-10 20:43 UTC, danielkrupinski requested changes
OR (`||`) is incorrect here.

2021-07-10 21:29 UTC, bruhmoment21 commented
> OR (`||`) is incorrect here.

fixed

2021-07-12 12:57 UTC, danielkrupinski approved these changes

2021-07-12 13:09 UTC, danielkrupinski approved these changes

2021-07-12 13:09 UTC, merged

2021-07-12 13:09 UTC, danielkrupinski commented
Thanks!